### ISSUE TITLE
How to access Message Manager

### ISSUE THREAD

**Issue by miamijerry** [rstrouse/nodejs-poolController-dashPanel#10]
How do we access Message Manager? 

I could not find any instructions !

**Comment by rstrouse** [comment]
A bit behind on docos.   Simply access it by adding /messagemanager.html to the url you launch dashPanel with.

**Comment by miamijerry** [comment]
I get
Cannot GET /messagemanager.html

**Comment by rstrouse** [comment]
That is very odd.  Does dashPanel load in the browser?  Just for shucks.  Capitalize the second m.  So messageManager.html

**Comment by miamijerry** [comment]
Capital M works, Thanks
