### ISSUE TITLE
Ph and Orb updating ??

### ISSUE THREAD

**Issue by miamijerry** [rstrouse/nodejs-poolController-dashPanel#11]
Previously reported here;
https://github.com/tagyoureit/nodejs-poolController/issues/228

At times the PH and ORB readings are not updating, at times they do.
Also the Intelliclor shows green after pumps stop. Reloading the page will update PH, ORB and Intellichor status.

Maybe related to the 15 minute delay that the Intellichem has before it will display PH and ORB readings.

![Chemistry 1](https://user-images.githubusercontent.com/8471168/95089590-4f774180-06f2-11eb-8285-181f27438eb5.JPG)
Pump starts, 15 min intellichem delay starts, Intelliclor shows green.

![chemistry 2](https://user-images.githubusercontent.com/8471168/95090944-da0c7080-06f3-11eb-9099-9eb3293873fa.JPG)
After Intellichem 15 min delay completes, requires page reload, then show PH & ORB

Yesterday PH & ORB were updating without page refresh, but not today. 
![git status](https://user-images.githubusercontent.com/8471168/95093587-efcf6500-06f6-11eb-8a22-a31552b129e0.JPG)
Same status as yesterday when it was updating.

Google chrome

**Comment by rstrouse** [comment]
Did you do a git pull?  There was a scenario where the chemController was not processing the change event.  This has been fixed.  You must restart dashPanel after you do it.  I would also go to your njspc directory and do a git pull there as well.

Could you please click on the balance then take a screenshot of the displayed screen.

Also, what OCP do you have (e.g. IntelliTouch i9+3, EasyTouch 4P, ... etc?

**Comment by miamijerry** [comment]
Seems to be working fine today. Did git pulls, rebooted, restarted webpages.
Easytouch Aux 8 OCP. I will check thru the day...
Rock solid
