### ISSUE TITLE
Intellichlor light stays on after pumps stops, rebooting RPI corrects.

### ISSUE THREAD

**Issue by miamijerry** [rstrouse/nodejs-poolController-dashPanel#12]
What is turning on the green box in front of "Intellichlor" in the dashpanel? Seems to indicate that the Intellichlor is working. 

Issue is that my light does not go off after the pump stops for the day. Reloading the web pages does not correct the light, rebooting the RPI does turn off the light.

**Comment by rstrouse** [comment]
The IntelliChlor messaging is very odd.  We have one other user where the messages simply stop being broadcast.  It simply loses communication and doesn't say a peep.  This is only with the most recent versions of IntelliChlor.  Have you managed to load up messageManager and are you willing to capture just the IntelliChlor messages for me when you cycle the pump on then off?

**Comment by rstrouse** [comment]
Hey wait a minute.  Do you also have IntelliChem?  IntelliChem takes over control of the IntelliChlor so maybe the OCP doesn't broadcast the requisite messages and leaves this up to IntelliChem.  Maybe the bit is on another message.

**Comment by miamijerry** [comment]
Yes, the Intellichem is supposed to be controlling the Intellichlor.

Are far as capturing commands I am at your disposal. I got into MeassageManager, but could not figure out anything. Slow learning curve for me...

**Comment by miamijerry** [comment]
OK, I resolved this issue. I had a secondary safety device which cuts the power from the Intellichem and intellichlor, when the pump is not running. This was a backup in case of a stuck flow switch(s). 

Once I bypass the device and the intellichem remains with power, the Intellichlor light on the dashPanel goes out within a minute of the pump stopping.
