### ISSUE TITLE
Can't change server if current server isn't found

### ISSUE THREAD

**Issue by tagyoureit** [rstrouse/nodejs-poolController-dashPanel#13]
See screenshot.  When I switch back/forth between different servers sometimes they are not up and running.  When it isn't reachable the toolbar doesn't display and I need to change the config.json manually.  

![2020-10-09_07-24-37](https://user-images.githubusercontent.com/1646840/95595210-c36e5e00-0a00-11eb-97e1-2fae98cb35bc.png)

**Comment by rstrouse** [comment]
This has been fixed.  The header will show with an Unknown controller when it cannot be ascertained.
