### ISSUE TITLE
Adjustable Format for one column view?

### ISSUE THREAD

**Issue by loopy321** [rstrouse/nodejs-poolController-dashPanel#14]
I was hoping to find a way to allow dashpanel to fit to one column so that it fits better on a phone screen.  The current version truncates the edges of the dashpanel and is not slidable to view it (see image below).

Great tool!  Thank you.
<img width="375" alt="PNG image" src="https://user-images.githubusercontent.com/1026345/97185030-9692a880-176d-11eb-9679-cf46353cfc24.png">

**Comment by rstrouse** [comment]
When I get some time I plan on adding some responsive css to the page.  The first step in this was to get the theme interface working and move all dimensional stuff to logical units which it is now.  I will be undertaking the next step next month to move the interface into a single column.

**Comment by rstrouse** [comment]
Grab a new dashPanel it now includes css for a mobile devices.  Unfortunately you will probably have to clear your browser cache as  the caching mechanisms for the css have yet to get an update.

**Comment by loopy321** [comment]
Thank you!  Got it working as expected in safari and chrome (incognito).  The update did not take on chrome (non-incognito) even after clearing cache - weird.
