### ISSUE TITLE
Schedule Editing not working correctly on EasyTouch2_8

### ISSUE THREAD

**Issue by jrhubott** [rstrouse/nodejs-poolController-dashPanel#17]
Editing pool schedule on EasyTouch2_8 doesn't work correctly.  See screenshots.

The Pools and Jets schedules are correctly displayed as Every Day on the main screen.  When editing they are only displayed as enabled for Sun / Mon / Tues and any attempts at editing them fails.

![Screen Shot 2021-01-20 at 17 58 42](https://user-images.githubusercontent.com/3378004/105269661-426b4a80-5b49-11eb-9421-c12f53b928a4.png)
![Screen Shot 2021-01-20 at 17 58 57](https://user-images.githubusercontent.com/3378004/105269667-44cda480-5b49-11eb-8443-b6b12527b2fd.png)
![Screen Shot 2021-01-20 at 17 59 12](https://user-images.githubusercontent.com/3378004/105269681-47c89500-5b49-11eb-99f5-eb6c648e3361.png)

**Comment by rstrouse** [comment]
Please pull a new njspc and dashPanel.  The bit flags for the days ET have been normalized so they should decode correctly now.  If you are not running the next repo of njspc please change to that.  It will contain the most recent changes.

**Comment by tagyoureit** [comment]
These should be fixed now.  Please pull both njsPC and dashPanel and changes were needed on both code bases.

**Comment by jrhubott** [comment]
This corrected the problem.  Issue is resolved.  Thanks!
