### ISSUE TITLE
Setting Schedules not working

### ISSUE THREAD

**Issue by johnny2678** [rstrouse/nodejs-poolController-dashPanel#20]
question on schedules - I went to change a schedule and got the message that Display is required...
![image](https://user-images.githubusercontent.com/8219743/108628706-619c1700-742a-11eb-9af8-c44eea813843.png)

clicked the dropdown for display and there's nothing to choose from - so seems like I can't edit schedules
![image](https://user-images.githubusercontent.com/8219743/108628715-68c32500-742a-11eb-83e6-8a344d23b44d.png)

not a big deal
btw, what is "Display"?

Botched1 @Botched1 09:25
@rstrouse Same here, can't edit or add schedules with dashPanel. Same issue as above - when saving a new or edited schedule it asks for a "display" but there is no display in the drop down. EasyTouch2 8.

This looks like #17 , but a little different.

Just pulled the latest njspc and dashpanel as of night of 2/20

**Comment by rstrouse** [comment]
Display allows you to set a rule as to when you would like the schedules to show on the dashboard.  The options are Never, When Active, and Always.  The Never and Always are obvious but When Active means that it should be shown when the schedule is currently triggered.

To resolve this issue you have two options.  

The first option is to pull dashPanel.   However, you must hard refresh your browser to have the changes take effect.  The caching mechanisms are a bit too aggressive in the software so it will continue to display the option.

The second option is to switch to the next repo.  To do this execute the following commands from the nodejs-poolController directory.
`git checkout next`
`git pull`
This will pull the latest code containing the support options for the display dropdown.
