### ISSUE TITLE
Start with PM2

### ISSUE THREAD

**Issue by brentratliff** [rstrouse/nodejs-poolController-dashPanel#21]
The wiki has a script that successfully starts poolController and the webClient. I am using dashPanel instead of webClient but it errors out when trying to start with PM2 when calling npm start from the dashPanel cwd. I'm sure it's a configuration difference in the script between webClient and dashPanel other than the cwd. Do you know anyone who has this working to post to the Wiki?

**Comment by tagyoureit** [comment]
I can add a section for dashPanel, but 'pm2 start dist/app.js' from the dashPanel Dir will get you there.

**Comment by tagyoureit** [comment]
See https://github.com/tagyoureit/nodejs-poolController/wiki/Automatically-start-at-boot---PM2-&-Systemd.  Docs are updated.
