### ISSUE TITLE
FEATURE REQUEST: pause chem dosing in dashPanel

### ISSUE THREAD

**Issue by johnny2678** [rstrouse/nodejs-poolController-dashPanel#22]
Selfish feature request to add a pause button for chem dosing (at least pH).  Maybe on this screen?

![image](https://user-images.githubusercontent.com/8219743/110245058-b6ae5180-7f2f-11eb-9454-c239f2f776ca.png)

Reason is to allow some time for chemicals that are manually added (Baking Soda, CYA, etc) to have time to mix.  Both chemicals get pH out of whack for a while.

Currently have to go into dashPanel settings to uncheck `pH enabled` and `ORP enabled` under `Chemistry` settings

Bonus points for a 'restart chem dosing after X hours/minutes" setting so I don't have to remember to unpause ;)

low priority

**Comment by rstrouse** [comment]
Go ahead and pull njspc, REM, and dashPanel.  You should now have the ability to set a manual mix cycle as well as cancel a current one.
![image](https://user-images.githubusercontent.com/47839015/113046109-7e77e880-9154-11eb-963b-5f06c920aa72.png)

**Comment by johnny2678** [comment]
ok, and just to make sure I'm thinking about this correctly... if I want to pause pH dosing for 4 hours, I set the mixing time for 4 hours and acid will not dose during that time.  Is that right?

If so, that is perfect.  Will really help when I add Baking Soda to up the ALK.  Causes the pH to spike and acid pump to kick in. But if I let it settle with the pump on (mixing), it stabilizes.   Should help save some acid. thx!

**Comment by rstrouse** [comment]
That is correct.  That is what mixing is for.... to mix the stuff in the water.  Chemical will not dose while it is mixing and the countdown will go from the mixing time you set.

**Comment by rstrouse** [comment]
Oh and one more thing if the mixing time is set to mix only when flow is detected it will make sure there has been flow for the amount of time you set.

**Comment by johnny2678** [comment]
> Oh and one more thing if the mixing time is set to mix only when flow is detected it will make sure there has been flow for the amount of time you set.

ok, this broke my brain a a bit.  Or I'm just really dense... manual mixing happens in the future (after you set a mixing time), so it checks to see that there "has been" flow in the past for the time you set into the future?

Or are you saying that when you set mixing time, it only counts towards that mixing time when there is flow.  e.g mixing time of 4 hours set 2 hours before pump is scheduled to go off. So it mixes for 2 hours today and the first 2 hours of the next day before dosing can continue.  Is that the case?  Really slick if so.

**Comment by rstrouse** [comment]
It only counts toward mixing time when flow is detected.  Go ahead and set a manual mix then turn off the pool.  You will see that the countdown will pause.  Then go ahead and turn it back on and you will see the mix time resume.  Then you can simply cancel the mixing and it will go back to where it was when you left off.  The above action is based upon the Mix only when flow detected checkbox.

**Comment by johnny2678** [comment]
cool implementation, looks like it's working great!
