### ISSUE TITLE
Spillway Feature Circuit causes DashPanel to report 'Timeout' when turned on

### ISSUE THREAD

**Issue by theRealMCQwerty** [rstrouse/nodejs-poolController-dashPanel#24]
Replay attached
[replay.zip](https://github.com/rstrouse/nodejs-poolController-dashPanel/files/6332665/replay.zip)

I added a new Feature Circuit via DashPanel and set the type to `Spillway`. Whenever I turn on this Feature Circuit DashPanel reports Timeout until the circuit is turned off.
![image](https://user-images.githubusercontent.com/26889036/115170197-ad171e00-a085-11eb-8522-f256c26be16b.png)

I tried changing a different Feature Circuit to type `Spillway` and it causes the same timeout issue message.
It doesn't seem to stop DashPanel from working but it is a bit concerning.

I hope the attached reply files provide the required info but please let me know if there is anything else you need in order to diagnose.

Thanks

**Comment by rstrouse** [comment]
Funny I just noticed this today.  Apparently IntelliCenter reports these bits on the same byte as the mode byte.

**Comment by rstrouse** [comment]
This byte translation is fixed and the Timeout no longer appears when you select a spillway circuit.

**Comment by rstrouse** [comment]
This was fixed a while ago so I am going to close this issue.  If you have any other issues please submit another issue.
