### ISSUE TITLE
heat set point range is Fahrenheit only

### ISSUE THREAD

**Issue by emes** [rstrouse/nodejs-poolController-dashPanel#25]
scripts/bodies.js seems not to be checking temp units for min/max

```
$('<div></div>').appendTo(evt.contents()).valueSpinner({ canEdit: true, labelText: 'Set Point', val: settings.setPoint, min: 65, max: 104, step: 1, bind:'heatSetpoint', units: '<span>&deg;</span><span class="picTempUnits">' + units + '</span>', labelAttrs: { style: { marginRight: '.25rem' } } });
```

range for Celsius should be 5-41

<img width="738" alt="Pool_Control_Dashboard" src="https://user-images.githubusercontent.com/363010/116361822-66d16580-a7cf-11eb-9ce1-a25df7a6e068.png">

![IMG_2732](https://user-images.githubusercontent.com/363010/116362044-a1d39900-a7cf-11eb-83dc-8363f7841f31.png)

![IMG_2733](https://user-images.githubusercontent.com/363010/116362062-a8621080-a7cf-11eb-837d-65e1e9790dc5.png)

**Comment by emes** [comment]
also, unrelated, but you can see from image that unused spa body and circuit re-appeared in last 48 hours, just fyi

**Comment by rstrouse** [comment]
Made this change.
