### ISSUE TITLE
Docker Request: Set config via Variables

### ISSUE THREAD

**Issue by noctividus** [rstrouse/nodejs-poolController-dashPanel#36]
Not sure if this is the right place, but it would be nice if the docker images allowed you to set some things via variables. 

I know this stuff gets saved in a config file if you use volumes, but it would be a nice feature to be able to set the server IP and port from a docker variable.

On the server docker image, it would be nice to be able to set the IP and port of the network RS485 bridge, or the name of the device (USB0, USB1, etc.)

**Comment by rstrouse** [comment]
Not familiar with docker but the config.json will not be overwritten if you include it your package.

**Comment by noctividus** [comment]
I guess this is the wrong place then! This stuff also being distributed via docker containers-

https://github.com/tagyoureit/nodejs-poolController/wiki/Docker

**Comment by rstrouse** [comment]
There were contributors to the nodejs-poolController repo that created the docker file (@wurmr @andylippitt @emes)  you can try to raise them directly in the [gitter](https://gitter.im/nodejs-poolController/Lobby) or mention them in an issue on the [nodejs-poolController](https://github.com/tagyoureit/nodejs-poolController/issues) repo.

**Comment by emes** [comment]
This has been added now.  I will update the wiki shortly.

you can set these env vars for njsPC

POOL_RS485_PORT
POOL_NET_CONNECT
POOL_NET_HOST
POOL_NET_PORT

and these for dashPanel:

POOL_HTTP_IP
POOL_HTTP_PORT

and they'll seed config.  Useful for what @noctividus described.

**Comment by rstrouse** [comment]
I am closing this as I believe @emes got it all squared away.
