### ISSUE TITLE
Trouble with DashPanel after install of 7.4 and rebuild of DashPanel

### ISSUE THREAD

**Issue by sparment** [rstrouse/nodejs-poolController-dashPanel#38]
I updated to PoolController 7.4 and then wiped out my old dashPanel and installed via git. I ran "npm install" in the new dashPanel directory and it seemed to work. When I run "npm start" in the new dashPanel directory I get an error:

``
Updated configuration file
error: ENOENT: no such file or directory, scandir '/home/pi/pool-controller-dashpanel/nodejs-poolController-dashPanel/data/outQueues/' {"errno":-2,"syscall":"scandir","code":"ENOENT","path":"/home/pi/pool-controller-dashpanel/nodejs-poolController-dashPanel/data/outQueues/"}
info: Server is now listening on 0.0.0.0:5150
Error creating directory: /home/pi/pool-controller-dashpanel/nodejs-poolController-dashPanel/data/outQueues/ - Error: ENOENT: no such file or directory, mkdir '/home/pi/pool-controller-dashpanel/nodejs-poolController-dashPanel/data/outQueues/'
192.168.1.24 GET /
192.168.1.24 GET /config/web.services?null
``

**Comment by tagyoureit** [comment]
It looks like you have 2 nested directories and probably don't want that.  Follow the same [instructions](https://github.com/tagyoureit/nodejs-poolController#prerequisites) for the core app as dP, but instead use the git clone address of this repo: https://github.com/rstrouse/nodejs-poolController-dashPanel.git.

**Comment by sparment** [comment]
I figured out my issue.
