### ISSUE TITLE
New Install - Nothing showing on Dashpanel

### ISSUE THREAD

**Issue by bad350trk** [rstrouse/nodejs-poolController-dashPanel#40]
Hi.  TFP Member Turbo1Ton here.  

I just went through the install, using the TFP thread that MyAZPool put together, and when I get to the point of opening a browser and checking everything, the dashpanel in the browser is blank.  

![Browser](https://user-images.githubusercontent.com/25586223/142780936-4a9f1495-2ff8-430d-87bb-ef72117b8ed7.png)

I did notice that I was having the same errors as wesgipe indicated in the earlier blank dashpanel issue, from January.  I went through those steps and did not notice any difference.

Not sure where to go from here.  I'm going to add screenshots of my setup.  Maybe that will have clues as to what I'm doing wrong.

![2021-11-21-145957_1](https://user-images.githubusercontent.com/25586223/142781273-9d852c3a-746a-49d0-aac7-1d08ebafd4f7.png)

![2021-11-21-150349_2](https://user-images.githubusercontent.com/25586223/142781276-cec0e4bd-4ca8-4468-9342-a34bfa1eabdb.png)

![2021-11-21-150550_3](https://user-images.githubusercontent.com/25586223/142781277-40cf621a-282b-4367-9e58-9e53372ac536.png)

![2021-11-21-153532_4](https://user-images.githubusercontent.com/25586223/142781281-4021e7f9-6d55-4351-8c21-90cbd3de5440.png)

![2021-11-21-153549_5](https://user-images.githubusercontent.com/25586223/142781283-7a873e71-89f9-4b2e-ab41-46d9657ad4b7.png)

![2021-11-21-153600_6](https://user-images.githubusercontent.com/25586223/142781285-2ed393e2-82f0-402f-abe1-36ae1e68887b.png)

![2021-11-21-153612_7](https://user-images.githubusercontent.com/25586223/142781287-91b1a5dc-02ec-41c0-a6ef-2439c5143cae.png)

![2021-11-21-153623_8](https://user-images.githubusercontent.com/25586223/142781291-2f77dd89-d0c9-4d44-845a-77e562dd80a4.png)

![2021-11-21-153634_9](https://user-images.githubusercontent.com/25586223/142781296-1cf7d911-4fdd-462e-b06c-bd5edc1c90bb.png)

![2021-11-21-153641_10](https://user-images.githubusercontent.com/25586223/142781298-ed70a79d-f224-45e3-9710-017b4e87b46d.png)

![2021-11-21-153646_11](https://user-images.githubusercontent.com/25586223/142781302-d6710057-ae46-453f-ac75-0397c41155b2.png)

![dashpanel install_start](https://user-images.githubusercontent.com/25586223/142781307-4ffc5bb6-bba5-409d-9d00-f03418c13464.png)

Thanks,

--Jeff

**Comment by tagyoureit** [comment]
Hi and welcome.  Can you try just starting dashPanel with `npm start` (no &)?  Sometimes setting it to run in the background makes it do weird things.  

We highly recommend [PM2](https://github.com/tagyoureit/nodejs-poolController/wiki/Automatically-start-at-boot---PM2-&-Systemd#pm2) when you get everything up and running.

**Comment by bad350trk** [comment]
Ok.  Just restarted it with no & and I did not get any errors, but the DashPanel is still showing the same.

![2021-11-21-165801_1024x600_scrot](https://user-images.githubusercontent.com/25586223/142782340-cc4a28bb-6239-4750-8781-a0a3406a887b.png)

Once I get up and going, I will look at PM2.

Thanks

--Jeff

**Comment by tagyoureit** [comment]
![image](https://user-images.githubusercontent.com/1646840/142785922-036effa5-64b9-4fe6-a00a-2c79fa6f25f6.png)
Click the hamburger menu in the upper left and then go to the connections tab and put in the ip address of the njsPC server.  You can also try the Find Server button.

**Comment by bad350trk** [comment]
That's great!  That worked!

Now off to play with everything else. 

Thanks for the help!

--Jeff
