### ISSUE TITLE
Feature Request. History

### ISSUE THREAD

**Issue by mzuniga51** [rstrouse/nodejs-poolController-dashPanel#41]
Robert,

In my opinion, one of the most underrated features of Intellicenter is the history section and the multiple graphs it is allowed to display.  Unfortunately, the info is buried in several places.   It would be amazing to be able to see all what information on dashPanel.  

I know there is information available for fetching on temperature (air and water), pH, ORP and dosage.  The last one seem to be only available at the OCP and not at the IOS app nor at the Intellicenter web page.

Again thanks for all the good work!

MZ

**Comment by rstrouse** [comment]
I haven't looked at this in a while but originally I determined that the history was stored with the controller and not transmitted over RS485 but then again they didn't work in the original IntelliCenter firmwares so perhaps they fixed some of the warts with it.  

As an aside, have you seen the abilities of Influx and grafana.  These interfaces are supported directly and provide awesome displays, charts, and graphs historically and in real time.  With them you can track every aspect including circuits, schedules, temperature, chemistry readings, dose periods, pump stats and even plot the items together.  njsPC will send data that updates these in real time.

At some point we will allow embedding into dashPanel for these.

**Comment by mzuniga51** [comment]
If I could only have the technical abilities to do what my curiosity
demands!  But I'm willing to learn including burning a few things lol.  Is
there any good post you know about on how to implement Influx of grafana
for that purpose?  I'll start researching anyway.

Thanks!

**Comment by rstrouse** [comment]
There is a lot written about it on the web.  The data creation and updates are all automatic from njsPC.

**Comment by tagyoureit** [comment]
BTW, there is already the ability to see past 24 hours dosage history via dashPanel...
![image](https://user-images.githubusercontent.com/1646840/143318053-52742c7d-fafe-4381-b3db-e859f9bbed3b.png)

And here's a teaser of a Grafana dashboard to whet your appetite.
![image](https://user-images.githubusercontent.com/1646840/143318117-25f45549-2f81-42c5-a5eb-5f179d80833e.png)

**Comment by mzuniga51** [comment]
Amazing
