### ISSUE TITLE
A few minor bugs

### ISSUE THREAD

**Issue by mzuniga51** [rstrouse/nodejs-poolController-dashPanel#42]
Hi.  Over the last few weeks I have had the pleasure to test drive dashPanel and aside from thinking the work you have done here is nothing short from amazing I have found a few very minor bugs, some of them probably already know issues.  Nothing that needs your immediate attention but still, here they are in no particular order:

1. Intellichem button in main interface appears greyed out even when it is active
2. Changing values in Chemistry Settings page returns this error  "undefined chem controllers require a valid address"  and ApiError: undefined chem controllers require a valid address
    at IntelliCenterChemControllerCommands.setChemControllerAsync (/home/pi/nodejs-poolController/controller/boards/SystemBoard.ts:3887:51)
    at IntelliCenterChemControllerCommands.setChemControllerStateAsync (/home/pi/nodejs-poolController/controller/boards/SystemBoard.ts:3915:42)
    at /home/pi/nodejs-poolController/web/services/state/State.ts:35:61
    at Layer.handle [as handle_request] (/home/pi/nodejs-poolController/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/nodejs-poolController/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/pi/nodejs-poolController/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pi/nodejs-poolController/node_modules/express/lib/router/layer.js:95:5)
    at /home/pi/nodejs-poolController/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/pi/nodejs-poolController/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/nodejs-poolController/node_modules/express/lib/router/index.js:275:10)
    at /home/pi/nodejs-poolController/web/Server.ts:708:25
    at Layer.handle [as handle_request] (/home/pi/nodejs-poolController/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/nodejs-poolController/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/nodejs-poolController/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/nodejs-poolController/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/nodejs-poolController/node_modules/express/lib/router/index.js:275:10) 
3. Timezone cannot be changed from dashPanel
4. In my setup where I have two valves (pool water feature and spa jets) only one of them is showing
5.  Don't know if possible and not a but really but it will be great to be able to reset OCP from dashPanel

Thanks!!

**Comment by rstrouse** [comment]
Thanks for the information.  I don't have IntelliChem so I need some additional info.

1. I assume you are talking about the little green indicator in the Chemistry panel.  This is supposed to illuminate only when the controller is dosing.  If it is in mix or monitor mode it should be grayed out.  It is possible that we are not getting the status set correctly.
2.  I'll figure out why the IntelliChem address is not being sent with the request.  To be sure this is from the Chemistry Settings popup window correct?
3.  I will have a fix soon.  The timezone settings changed from v1.023 firmware and I never went back to change it.
4. Which panel do you have is it an i8P or an i8PS
5. Yeah you can't do it from an indoor or wireless controller either.

**Comment by mzuniga51** [comment]
Sure Robert.

1.  Haven't verified but in my mind green shoud indicate IntelliChem is in
working order and maybe another color or blinking for dosing or mixing
2. Correct
3.  👍🏻👍🏻
4. i10D
5.  Got it.

Thank you!

**Comment by rstrouse** [comment]
Yeah CRS kicked in I remembered i10D shortly after I posted.

**Comment by rstrouse** [comment]
Hey how many valves are supported directly with i10D without a valve expansion module?  Is it 2?

**Comment by rstrouse** [comment]
Ok so I did some research and indeed the i10D is valve count is 2.  So if you pull njsPC then reload the config it should find the additional valve if the numbering remains the same as other panels.

Also, I believe I fixed the IntelliChem address from the Chemistry Settings window and the timezone setting.  So you should pull a new njsPC
`cd ~/nodejs-poolController`
`git pull`

Then navigate to the System tab under the hamburger menu and press reload config.  It will start pulling the basic information from the panel and continue to request items until it has exhausted the relevant panel data.

Let me know if the issues have been fixed since I do not have the same equipment.

**Comment by mzuniga51** [comment]
Correct. Two.

**Comment by mzuniga51** [comment]
Chemistry and timezone are resolved and valve 2 is present.  Thank you!
Just another detail I just found, I requested Filters to be hidden in
Settings/Appearance and it appears so in there but it will shows again in
dashPanel after reloading the webpage (still appear as hidden in
Appearance).

**Comment by mzuniga51** [comment]
Scratch that. It is happening with all boxes.  All get unhidden after
reloading the page.

**Comment by rstrouse** [comment]
The filters section order and display have been fixed.  pull dashPanel
`cd ~/nodejs-poolController-dashPanel`
`git pull`

Keep in mind these settings are local to the client browser.  The configuration and display is unique per device.  This allows a different display and order for a wall controller for instance vs your iPad.

**Comment by mzuniga51** [comment]
Thank you. Yes, i had figured as much.

**Comment by mzuniga51** [comment]
Sorry, still same behavior.  I hid filters or any other panel, they
reappear after reloading the page.

**Comment by rstrouse** [comment]
You must hard refresh because I am lame and haven't written a cache expiration for dashPanel script.  You also must get it to write out to the browser by unhiding and re-hiding.  Unfortunately, the local storage on the browser didn't originally have the data.

**Comment by mzuniga51** [comment]
Got it.  Will do.  Thanks

**Comment by rstrouse** [comment]
I am going to close this.  If you have any more issues submit a new issue.

**Comment by mzuniga51** [comment]
Sure.  thanks!
