### ISSUE TITLE
Missin Schedules

### ISSUE THREAD

**Issue by mzuniga51** [rstrouse/nodejs-poolController-dashPanel#47]
Hi Robert.  Im now running the controller from my mac mini server and using the Elfin wireless adapter for comms.  Much more stable now.

However I’ve run into an issue where not all schedules created at the OPC or the app appear in the dashPanel.  No idea what might be causing that.  See images attached.

![69D9373F-ABBB-409E-A688-270785DF401E](https://user-images.githubusercontent.com/91519307/147393863-a9a6d2ba-c14b-4fb3-b657-a26597c1860d.png)
![9AF7FEA7-33A4-4DBE-8243-3F3170AD286A](https://user-images.githubusercontent.com/91519307/147393864-f3cad312-d142-421b-9faa-b8d35910fe5a.png)

**Comment by tagyoureit** [comment]
Can you try to change the end time of the spa 12am-12am schedule?  Maybe it has to due with the same start/end time?  Do you have it set as 12-12 or is it actually set as "don't stop" in the schedule definition?

**Comment by mzuniga51** [comment]
So, apparently if you create a 24h schedule in OCP or app it will not
appear in dashPanel.  That is true even if later you modify that same
schedule to other than 24 h.  Im not using the “dont stop” option.
Conversely, I found that i can create a schedule for less than 24h and
later change it to 24 h and then it will appear in dashPanel no problem.
Go figure!

On an unrelated issue, could you consider adding a tab in the home menu to
be able
to configure the spa side remote (is4)?

Many thanks as always.

**Comment by rstrouse** [comment]
This actually had to do with changes that were not picked up from IntelliCenter where the schedule was not being set as active when the start or end times were midnight.  This has been fixed if you pull njsPC and dashPanel.  After you pull the repos please hard refresh your dashPanel display then go to the hamburger menu and click on the system tab.  Then press the Reload Config button to pull all the schedules from the OCP.

I would love to add a spa side remote tab.  Unfortunately, I do not have one but if you are willing to go through some testing I can get one added.

**Comment by mzuniga51** [comment]
Thank you.  At the moment i only have one of the buttons in the remote
working and the rest seem to have been given up so I’m actually thinking
about replacing it.  I dont know if I can still help you.

By the way, I have Intellibrite lights and would like to use the “hold” and
“recall” functions from dashPanel.  Is that currently available?

Thanks and have a great new year!

**Comment by rstrouse** [comment]
I checked in some additional functions for the Hold/Recall in IntelliBrite.

**Comment by mzuniga51** [comment]
Great.  I try it later today

**Comment by mzuniga51** [comment]
So i can see the recall and hold button in my mac browser but not in my
ipad or iphone browser.  Funny.

Btw, I have now influx and grafana working and i see a lot of data from the
Intellicenter.  However I cant see certain data from my Intellichem (say
every time the Intellichem tells my CO2 tank to dose).  Do you think there
is a way to extract that information?  Intellicenter must have that data
from the Intellichem i reckon... Would you like to work with me on this?

Thanks!

**Comment by rstrouse** [comment]
You need to hard refresh the browsers on your ipad and iphone.  Unfortunately, Apple is braindead about that and don't allow you to clear the cache without going through settings.  You can try to wait for Apple to refresh sometimes it takes a day or so.

As for the CO2 tank dose we scrape every bit of information that IntelliChem puts out so I would assume that it tells when the dose occurs.  Unfortunately, I do know that you won't get any data about how much was dosed.

Here are some of my grafana graphs related to REM Chem.

![image](https://user-images.githubusercontent.com/47839015/148623500-5b28e759-fa6c-4492-a96c-93d9246e79b3.png)

**Comment by mzuniga51** [comment]
Thank you Robert.  Would it be possible for you to share some of your
grafana templates with me?  No swear if you prefer not to.  Thanks!

**Comment by rstrouse** [comment]
Here you go.
[Pool General-1641605165918.json.txt](https://github.com/rstrouse/nodejs-poolController-dashPanel/files/7832139/Pool.General-1641605165918.json.txt)

**Comment by mzuniga51** [comment]
Robert youre the best. Thanks a bunch.
