### ISSUE TITLE
Unable to change Chemistry Settings

### ISSUE THREAD

**Issue by mzuniga51** [rstrouse/nodejs-poolController-dashPanel#48]
In the Chemistry Settings window I'm unable to change values as they tend to revert to their original point.  Also I have no way of imput values in there from my ipad keyboard.

See capture attached
[replay.zip](https://github.com/rstrouse/nodejs-poolController-dashPanel/files/7873765/replay.zip)

**Comment by rstrouse** [comment]
Pull njsPC and try again.  The message routing appears to have been incorrect.

**Comment by mzuniga51** [comment]
Thanks.  Still quite unresponsive.  It seems that sometimes it does want to change the value after a while, but also randomly revert to the original value.  This happens both to the set points as well as in the Index Values settings.  

Also there is no way to input the number from a keyboard  in any of the values so for example if CH is in 1 you have to press the +button 349 times to get to 350

**Comment by rstrouse** [comment]
Can I get you to do a replay  where you set the tank levels from IntelliCenter or is this feature not available.  It looks like it has been removed.

EDIT:  I fixed the ability to edit inside the spinners on dashPanel.  You will however have to clear the cache to get it to load the css and pull dashPanel.

**Comment by mzuniga51** [comment]
Here is the replay.  This is how my chemistry page looks like.  My setup is an Intellichlor and CO2 tank.  Intellichem only controls the CO2 dispensing and chlorine dispensing hardware is set to “none”.  Still Intellichem seem to believe that I have acid and chlorine tanks and displays the chlorine tank as empty and the acid tank as
full.  Go figure! Pentair really needs to step up the game with these products.

[replay 7.zip](https://github.com/rstrouse/nodejs-poolController-dashPanel/files/7890373/replay.7.zip)
![A4D93AA8-684E-4536-846B-FDDEDD3F97BD](https://user-images.githubusercontent.com/91519307/149971591-22fe4133-6276-4c6c-9653-8890442e36c7.png)

**Comment by rstrouse** [comment]
So what you are saying is that the tank levels are disabled in the IntelliCenter control panel when you are using CO2 control.  Is that correct?

Either way thanks for the replay.  It was really important to know that you were using CO2 for pH control.  I need to know what some of your IntelliChem is settings are.  Honestly, I do think that many of these dosing systems could do for a good overhaul.  For most of them CO2 dosing looks a lot like and afterthought but there are fewer overdosing concerns with CO2 since you can only dissolve so much CO2 into solution before it off-gasses.

I will focus on the pH settings first then we will tackle whether there is any information in the output to deal with the ORP side.
* Is your setting for the pH control set to CO2 Ext/Relay (CO2/R2) or is it simply set to one of the Relay 1 or 2 settings?
* Do you have the CO2 dosing set up for Time or to Setpoint?
* If it is to Setpoint what dose limit do you have set?
* If it is by time what dose time and dose limit do you have set?

**Comment by mzuniga51** [comment]
`So what you are saying is that the tank levels are disabled in the IntelliCenter control panel when you are using CO2 control. Is that correct?`

Well, yes and no.  The tanks appear but seem to be only for decorative purposes and not changeable like this:
<img width="539" alt="Screen Shot 2022-01-18 at 14 46 04" src="https://user-images.githubusercontent.com/91519307/150016219-bc252eb8-cb3e-4e0c-b151-0b4a172ff30d.png">
 
`Honestly, I do think that many of these dosing systems could do for a good overhaul. For most of them CO2 dosing looks a lot like and afterthought but there are fewer overdosing concerns with CO2 since you can only dissolve so much CO2 into solution before it off-gasses`

Yes, I bought my system before reading the awful reviews in TFP.  Now, four months into installation I have to say that the CO2 system works like a charm.  pH 7.6 at all times with TA on a very steady 70-80.  That being said the jury is still out on the long term.  

`Is your setting for the pH control set to CO2 Ext/Relay (CO2/R2) or is it simply set to one of the Relay 1 or 2 settings?`
CO2 Ext/Relay.  See picture:
![IMG_2197](https://user-images.githubusercontent.com/91519307/150017195-3f1d8122-aef7-4dc5-aeae-3dcdba72b39d.jpg)



Do you have the CO2 dosing set up for Time or to Setpoint?
Time.  I tried Setpoint but one time my pH was so high that the system burned though whole tank.  I don't think this will happen to me again but still now I prefer to set it to a maximum of 15 applications of 1 minute over a 24 hour period with 30 min mixing time with seem to give me the perfect maintenance dose.  If the pH is still high (which hasn't been the case lately) then I apply CO2 manually or in a extreme case by adding acid.  See pictures: 
![IMG_2201](https://user-images.githubusercontent.com/91519307/150017641-dfe97d10-fa9b-4a48-9409-b7cc80819a71.jpg)

![IMG_2202](https://user-images.githubusercontent.com/91519307/150017532-cbbcf04d-7e25-4af1-8a25-426c1cebf8f7.jpg)
All this on trial and error because Pentair provides zero support to CO2 users.  On top of that you also need to set your regulator physical output at the tank, which is not controlled by the Intellichen but by a flow valve.  Again, that was trial and error.

**Comment by rstrouse** [comment]
Are both of your IntelliChems set up as `[CO2/R2 IChlor]` or is 1 set up as `[CO2/R2 L_Relay]`.  This determines which doser is connected.

**Comment by mzuniga51** [comment]
Well, interesting question.  When I configured the Intellichlors via the
Auto Setup menu I did [CO2/R2 Ichlor].  Later when decided not to use the
automation for the chlorine I went to Configuration--Hardware--ORP hardware
and change Chlorine from [INTELLICHLOR] to [NONE].   I know that if i go
again to Auto Setup and configure [CO2/R2 Ichlor] the the hardware
configuration reverts from [NONE] to [INTELLICHLOR].  Currently both are in
[NONE].

Notice that I don't know what [NONE] in the hardware configuration is
equivalent in terms of the [CO2/R2 IChlor], [CO2/R2 L_Relay] or other
options acording to the syntaxis used on the Auto Setup means. When you do
Auto Setup you are always taken to [CO2/R2 IChlor] as first item in the
menu.    Difficult to explain but I hope you somehow grasp my meaning.

**Comment by rstrouse** [comment]
Yes that does clear up what I am seeing.  The reason I asked is because I could not figure out what I was seeing from the configuration.  The docs do not describe such an option for the doser type and the IntelliChlor bit was off.  Sadly, IntelliChem also does not send any indication that it is using CO2 as a doser type.  So unfortunately, I cannot figure out how to make the tank display disappear.

**Comment by mzuniga51** [comment]
Crazy how half baked this system is and how little they care for their ongoing progress of it.  Let me check over the next few days if the Chemistry Settings can now be changed from dashPanel.  Thanks Robert.

**Comment by rstrouse** [comment]
Pull njsPC and dashPanel I added some settings to better represent CO2 dosing.  Unfortunately, it doesn't improve much other than remove settings that are not relevant.

**Comment by mzuniga51** [comment]
Thank you Robert!
