### ISSUE TITLE
Issue with ORP alarm (low priority)

### ISSUE THREAD

**Issue by mzuniga51** [rstrouse/nodejs-poolController-dashPanel#49]
Robert, not something terribly important but:

I keep my pool at CYA of 50 and FC 5 per TFP recommendation for Salt pools.  I have found that a ORP level of 630 or so roughly equates to that of my desired FC. A low value since naturally the CYA distorts the probe reading.

Now you know I'm not using the intellichem for chlorine control but I find it useful to give me that rough ORP estimate of when my chlorine would be high or low. Just a ver rough proxi.

So I set my ORP level at 630 at the Intellichem thinking that an alarm will trigger if the ORP is below 630.  In actuality tough, the alarm triggers when the level is below 650 wich seem to be the minimum ORP hard coded into the Intellichem (red bar area in the Chemistry Settings).

I dont use the Intellicenter's notifications but i keep having an "ORP Level Low" warning at the dashPanel that triggers my OCD.  So, would you consider adding a way to disable those warnigns as a setting in dashPanel?

Thanks

**Comment by rstrouse** [comment]
This function already exists in dashPanel.  If you go to the configuration page in dashPanel for IntelliChem you will see an alarms tab where you can set the ranges.  Sadly you will still get the LSI warnings from IntelliChem but you can control the other limits.
![image](https://user-images.githubusercontent.com/47839015/150688368-562996c2-1e10-4acc-8eeb-83dcde5149fd.png)

**Comment by rstrouse** [comment]
Pull njsPC IntelliChem was overwriting our alarm data.

**Comment by mzuniga51** [comment]
[replay.zip](https://github.com/rstrouse/nodejs-poolController-dashPanel/files/7921650/replay.zip)
And here is the alarm still on in the main panel after deactivating the ORP alarm
![B08944A5-9F0C-47F3-82EB-545BBD04D15C](https://user-images.githubusercontent.com/91519307/150701904-8f86e506-b92b-4f3b-a2cd-4e304a13eee2.png)
Also I just lost the whole Chemistry Settings window.  Nothing happens now when I click on the Intellichem
