### ISSUE TITLE
Feature request: Hide a body in the dash panel

### ISSUE THREAD

**Issue by terafin** [rstrouse/nodejs-poolController-dashPanel#51]
**Describe the request**
I have an Easytouch8 which has 2 bodies, pool and spa - however I only have a single pool. Would love to disable the Spa body somehow, as it's just cluttering up the UI!

**Comment by rstrouse** [comment]
If you pull njsPC and dashPanel.  There is now a checkbox in the body configuration that will allow you to hide the body by unchecking the Show in Dashboard checkbox.

**Comment by rstrouse** [comment]
@terafin did this work for you?

**Comment by rstrouse** [comment]
I assume this worked for your purpose.  Closing this for now.

**Comment by terafin** [comment]
@rstrouse My apologies, didn't see this for some reason. I updated, and can confirm this worked. Thanks!
