### ISSUE TITLE
Changing Intellichlor output upon circuit switch on

### ISSUE THREAD

**Issue by mzuniga51** [rstrouse/nodejs-poolController-dashPanel#53]
The idea is being able to deliver 100% output from the Intellichlor cell when a specific circuit is turned on.  In this case, the idea is that Spa receives full cell output when heating which is when the chlorine consumption has an abnormal peak.

**Comment by rstrouse** [comment]
Post up your current njsPCAux.json file.

**Comment by mzuniga51** [comment]
Here.  Included the last attempt that didn't wor
[njsPCAux.txt](https://github.com/rstrouse/nodejs-poolController-dashPanel/files/8310559/njsPCAux.txt)
k

**Comment by rstrouse** [comment]
Here is the section for setting the chlorinator.
```
    {
      "name": "virtualCircuit",
      "description": "Set the superchlor when the spa heater turns on or off",
      "body": "@bind=extend(true, {}, {id: 1, isDosing: data.isOn});",
      "enabled": true,
      "options": {
        "host": "192.168.68.165",
        "port": 4200,
        "method": "PUT",
        "path": "/config/chlorinator"
      },
      "filter": "@bind=data.id === 245;"
    }
```

**Comment by mzuniga51** [comment]
Now I can briefly see a super chlorinate message but then it immediately disappears.  Percentage output stays the same though.

**Comment by rstrouse** [comment]
Now I need a capture when the heater is going on then when it is going off.   This should not be changing the setpoints only increasing the output.  We have to fool IntelliCenter because it will try to set it back.

**Comment by mzuniga51** [comment]
Here is the capture
[replay.zip](https://github.com/rstrouse/nodejs-poolController-dashPanel/files/8312216/replay.zip)

**Comment by tagyoureit** [comment]
BTW, just for clarity of definitions...

Super Chlorinate has a duration and sets the chlorinator to 100% _and_ ensures that the pool (or spa) stay on for the length of the super chlorinate function.  It will return the chlorinator back to the previous output % after super chlorination is finished.

I think you just want to set the chlorinator to 100% but technically this isn't super chlorinating.

**Comment by mzuniga51** [comment]
Correct.  The message that briefly appeared this last time said “Super chlor:” though.

**Comment by rstrouse** [comment]
Manuel,  I looked at the replay it is setting the chlorinator to 100% there may be some delay with this but the cell is definitely ramping up to 100% and returning to the original setpoint afterwards.  This looks like it is doing what you want.
![image](https://user-images.githubusercontent.com/47839015/159190076-834582f9-39d7-4ad0-bb11-590d63c83684.png)

**Comment by mzuniga51** [comment]
Let me go and check it out directly at the cell

**Comment by rstrouse** [comment]
It may just take a bit to report to njsPC

**Comment by mzuniga51** [comment]
Success!  The cell is doing it.   It is just that njsPC is not reporting it even after 30 min but that is not a problem for me.  So long as it is happening!  As always, many thanks Robert

**Comment by tagyoureit** [comment]
Is it not reporting in both instances?

**Comment by mzuniga51** [comment]
I have set the value for 10% and is reporting correctly.  Once I set the
heater, the cell lights goes to 100% but njsPC keeps reporting 10%

**Comment by rstrouse** [comment]
Funny we are just spitting out the wrong value

**Comment by mzuniga51** [comment]
Lets take our (almost) success and call it a day! lol
