### ISSUE TITLE
Cannot select light color options

### ISSUE THREAD

**Issue by Candurin** [rstrouse/nodejs-poolController-dashPanel#57]
Upgraded from 7.1.0 to 7.7.0 and noticed that I cannot select the color palette on my microbrite lights (intellibrite in dashPanel).

This worked perfectly in 7.1, but not in the new version.

**Comment by tagyoureit** [comment]
First thing is to try a hard refresh of the browser. If on mobile, you'll need to clear the cache. Have you tried that yet?

**Comment by Candurin** [comment]
@tagyoureit I did.  Still no luck.

**Comment by tagyoureit** [comment]
I just tried and was not able to replicate this.  Can you attach a packet capture?  And also some screenshots of where you are having the issue?  And if there are any errors in the Javascript console those would be useful as well.

**Comment by Candurin** [comment]
I need some hand holding, lol.  Can tell me what commands to run?

**Comment by tagyoureit** [comment]
https://github.com/tagyoureit/nodejs-poolController/wiki/How-to-capture-all-packets-for-issue-resolution#-dashpanel

**Comment by tagyoureit** [comment]
Actually, pull dP and try again.  May have just fixed it (thx @rstrouse!).

**Comment by Candurin** [comment]
Thanks for the help! It is now working properly!

**Comment by rstrouse** [comment]
Great I am closing this.
