### ISSUE TITLE
Need ability to remove or hide second body of water 

### ISSUE THREAD

**Issue by thumbnut** [rstrouse/nodejs-poolController-dashPanel#60]
This app is fantastic. 

I have a single pool with no separate spa. The spa jets are in the pool. I have the IntelliCenter with i10PS and it assumes a second body. I was talked into getting this setup. No going back. I would like to have the ability to hide or delete the “pool 2” from the Dashboard. It has no functionality. I can uncheck it in settings but it re-checks itself. 
Thanks,

thumbnut

**Comment by tagyoureit** [comment]
Ok, I'll bite... what were you told to get you to buy a shared body system for a single body pool?  

And do you use the intake/return valves?  Or are your "jets" hooked up to a different valve?

**Comment by rstrouse** [comment]
Did you uncheck the Show in Dashboard checkbox under the gears menu in Bodies?

**Comment by thumbnut** [comment]
@tagyoureit - I made a last minute purchase decision change from an IntelliTouch to the IntelliCenter, back in 2018. The Pentair rep talked me into it over the phone when I told him how many features and valves I needed. His brain got stuck on the 12 spa jets, but the fact that they were in the pool went in one ear and out the other. I had no knowledge of the part number differences and trusted the rep. He also talked me into the IntelliValves. Back then I got the story that "in the fall" they would be controlled by the RS485. This was a BYOP project, and the dealer did not know jack about the new hardware. He took the rep's word for everything. The pool build was a total disaster. By the time I was able to even think about the automation it was too late for returns.  As for the intake/return valves, I treat them as unusable. Using two other valves for that. I have no spillover. I am making lemonade, as they say.

@rstrouse - I know I unchecked the Spa in Bodies, but it would not stay unchecked. When I went back into the gears menu it was checked again. Must be automatically set by hardware ID. I cannot duplicate the issue since the whole thing is not working today. I spent most of yesterday setting this all up for the first time following Ron's tutorial on TFP, to the letter I might add.  Using a rpi 3B+, Samsung Evo+ 32GB card, and the nifty RS485 adapter https://www.amazon.com/dp/B081MB6PN2?psc=1&ref=ppx_yo2ov_dt_b_product_details .  I took three tries at running through the entire process and was not able to get the communication going. I have the pi and the IC board set up on my desk, along with one IntelliValve.  Both are on ethernet.  I finally tried the "Search for a server" on the third attempt and it connected. It was not able to use the explicit IP address, but the raspberrypi.hsd1.az.comcast.net:4200.  I was in poolController heaven for a few hours. Unfortunately I powered things down last night. Today it would not connect. I did not set up the auto start on boot so I manually went into the console and started both programs.
![image](https://user-images.githubusercontent.com/29102016/182010256-19f5a646-7df4-478e-9f6a-22516e56fc1e.png)
I only get what is in the pic.
I did end up modifying the rc.local file per instructions, but with no success. On a reboot I can not connect. I will try again tomorrow.
Let me know what else you need for log files or other info and thanks for your help.

**Comment by thumbnut** [comment]
Here is more info that may be helpful:

NPM version is 8.15.1

![image](https://user-images.githubusercontent.com/29102016/182012086-3a39cc43-274d-4344-aed6-d01df9ec31e8.png)


![image](https://user-images.githubusercontent.com/29102016/182011981-4ccbbc9c-6c15-4b02-87d8-35d17c409511.png)


![image](https://user-images.githubusercontent.com/29102016/182011999-1c771822-e6d0-416b-9ce3-91de3043c68b.png)


![image](https://user-images.githubusercontent.com/29102016/182012020-ef3a6a1a-e39e-4286-9bcb-4686ade17bd2.png)


![image](https://user-images.githubusercontent.com/29102016/182012822-a06ba7f3-1d8d-4696-8aaf-4e9ff5d6a4bd.png)


![image](https://user-images.githubusercontent.com/29102016/182012906-b1db68eb-5a11-4dd9-9a97-95a2d6a424b2.png)


![image](https://user-images.githubusercontent.com/29102016/182013122-e7d18465-3d8b-46c3-a0df-85f88319018a.png)

**Comment by rstrouse** [comment]
Ok lets do a couple of things first.  I just had another user that was seeing some weirdo stuff on their network.  Have you set up an IP reservation in your router.  Unfortunately many of these routers have spotty name service implementation.  

I just witnessed one of the xfinity routers changing ip addresses for components on the network randomly.  All of his connected devices would go haywire, including njsPC for a few minutes then would eventually come back.  I have my theories that some of it is related to QoS for streaming but instead of finding a new IP lease for a streaming port it would reassign connected devices.

Anyhow the fix was simple.  Assign a DHCP reservation for your Raspberry Pi.  This will ensure it does not reassign it to another IP address at random.  Then we do not have to rely on their DNS server resolving a proper IP address.   This looks like what comcast is doing with the callback to comcast.net servers.

If there is some sort of mobile app it probably does not contain functions to do this.  You will likely need to do this from their web app at `http://10.0.0.1`.

I will check to see if we are resetting the Show In Dashboard flag.  It is possible that IntelliCenter is indicating its existence and we just simply respond to it.  This is a function that IntelliCenter does not have but it does have it for the underlying spa circuit and we may be keying off of that.

**Comment by thumbnut** [comment]
I'm not sure it has anything to do with the router re-assigning IP addresses since I have 3 other rpi 3B+ that have been running 3D printers on the same network with no issue. It is ethernet, not WiFi. On WiFi we have had to do that with one IoT device that switched between 2.4 and 5 GHz randomly. The ethernet devices never change like that.
Is it possible to just force the dashPanel to use the explicit IP address of 1.0.0.29?  I have been using VNC viewer to run the pi using the IP address and it has been rock solid.

**Comment by rstrouse** [comment]
Yes simply type `10.0.0.29` into the address field in the connections tab.  njsPC will translate it.  DNS can be spotty depending on the modem.  This is especially true if there are devices on the network with duplicate host names.  For instance if there are 3 RPis and all 3 have the name raspberrypi then the DNS services start making stuff up for them and resolve to one ip addresses with that name.  Most likely it will be the last one that registered it.

If devices you are using on your network are dependent on their IP address it is wise to assign them a DHCP reservation though in the router.  It isn't typically that hard to do and it guarantees that the ip addressed are handed out the same way regardless of their position in the routing table.

**Comment by thumbnut** [comment]
Is it possible that there is something in the latest release of nodejs or
npm or debian causing trouble?
It looks like package-lock.json may be an issue.

![image](https://user-images.githubusercontent.com/29102016/182434985-7b74bec3-5ef5-44b2-9b0a-9725f23219b3.png)

**Comment by thumbnut** [comment]
I got the app running. (somehow). I used npm run start:cached instead of npm start. 

Anyway, back to the original request:

I uncheck  Show in Dashboard 

![image](https://user-images.githubusercontent.com/29102016/182440138-971a5349-8cbb-43f1-a775-400966117f25.png)


And as soon as I click Save Body...

![image](https://user-images.githubusercontent.com/29102016/182440829-69092cd9-166b-4dff-b748-fbfc1d4ab185.png)


It re-checks Show in Dashboard.

![image](https://user-images.githubusercontent.com/29102016/182440865-713ef4bb-2382-42c0-abd5-a55d9ff20046.png)

![image](https://user-images.githubusercontent.com/29102016/182441118-c76b258c-2bd1-40dd-bd89-7395e8049d14.png)

**Comment by rstrouse** [comment]
Hmmm... did you perform an `npm i` after the `git pull`?

EDIT: Pull njsPC, I found a path where certain boards were not persisting the showInDashboard flag.

**Comment by rstrouse** [comment]
Do you always have to run `npm i` with `sudo`.

**Comment by thumbnut** [comment]
I only did that as I have been grasping for straws in an effort to solve
the problem. Thought permissions may have been an issue.

**Comment by rstrouse** [comment]
Pull njsPC I fixed an issue with the property setter that may have been causing the issue.

**Comment by thumbnut** [comment]
Is it possible to get an updated install guide that references the latest
OS, Node, and NPM packages?   Am I the most recent install?

I am using the latest Raspberry Pi Imager, version 1.7.2, using an official
Rpi 3B+, and using the recommended micro-SD card.

**Comment by rstrouse** [comment]
Sure we have been working on our Quick Start Guide.
https://github.com/tagyoureit/nodejs-poolController/wiki/Quick-Start-Guide

**Comment by thumbnut** [comment]
It worked!
Thanks!
[image: image.png]

**Comment by thumbnut** [comment]
Seems to be working except I cannot save circuit groups or features. The
save button highlights but nothing happens.
My workaround is to use the IOS IntelliCenter2 app for those two operations.

[image: image.png]


[image: image.png]

**Comment by rstrouse** [comment]
Pull dashPanel and hard refresh your browser.  There was an issue with the Touch controllers that required a name identifier.  This function was causing the screen to fail the validation.

**Comment by thumbnut** [comment]
Tried that but same result. Rebooted the pi. Closed the browser. Used
different browsers. Delete works great. Just cannot add feature circuits or
circuit groups. I can add AUX circuits.

[image: image.png]

[image: image.png]

**Comment by rstrouse** [comment]
Ok I missed a couple of spots where the name identifier from Touch controllers was generating an error when saving.  Pull dashPanel and hard refresh your browser.

**Comment by thumbnut** [comment]
Bingo!

**Comment by thumbnut** [comment]
Issue with inability to remove or hide second body of water has been resolved.
Issue with inability to save Feature Circuits has been resolved.
Issue with inability to save Circuit Groups has been resolved.
Many thanks rstrouse!

**Comment by thumbnut** [comment]
This one is a minor nit but the valve type keeps returning back to
Standard. These were all labeled IntelliValve before restarting the app.

[image: image.png]

**Comment by rstrouse** [comment]
Yeah this is because the setting no longer sticks with the new IntelliCenter firmware so this will be normal until they add support.
