### ISSUE TITLE
Heater "Time to off" shows 1 hour countdown

### ISSUE THREAD

**Issue by thumbnut** [rstrouse/nodejs-poolController-dashPanel#62]
One thing I notice is that the "Time to off" does not reflect the Pentair settings for "Economy Time"

![image](https://user-images.githubusercontent.com/29102016/186757923-82f86b85-cdeb-48b3-886f-552472982cce.png)

Right after I started the heater it showed 59 minutes left, rather than 4 hours and 59 minutes. Here it shows 47 minutes left after it has been shut off and it continues to count down. There are features running so I am not sure if the big pool button should still be green with the heater off.

![image](https://user-images.githubusercontent.com/29102016/186758003-ac343134-8168-4059-bed6-96a442c18244.png)

**Comment by tagyoureit** [comment]
The big green button represents the pool circuit being on (and clear when it is off).  It has no bearing on the heater.

Likewise, the "time to off" represents the remaining time that the pool circuit should be on based on the schedules, egg-timer, etc.  However, it has no knowledge of "economy time".  If the economy time means that the pool will stay on longer than the schedule we might want to consider that (eg if the schedule is supposed to shut off the pool in 2 mins but the heater requires it to run for 5).

Can you tell me more about the Economy time and if it affects how long the circuit should be on?

**Comment by rstrouse** [comment]
Economy time only has to do with UltraTemp ETi Hybrid heaters.  The "economy time" is how long it will run the heat pump until it gives up and starts banging with gas.  So if the economy time is set to 1 hour and the heat mode is hybrid it will run the heat pump for an hour or until it reaches the setpoint.  If it does not get within the offset temperature within that hour it will turn on the gas heater to bring the temperature up to the setpoint.

All of this is internal to the heater and is not reported in any way that I am aware.

**Comment by thumbnut** [comment]
Thanks. I was searching the manual for "economy time" and no results. Manual shows it as Eco-time.
Got it now.
