### ISSUE TITLE
Pool shows off, when its on

### ISSUE THREAD

**Issue by camaro4life18** [rstrouse/nodejs-poolController-dashPanel#68]
I created a schedule to run the pump at a higher RPM to filter from 4am to 7:59am, then another schedule for the pump to run at a low RPM from 8am until 3:49am. The schedule runs fine, but when the filter circuit shuts off, it shows the pool as if it is off. If I open the pump controls, turn off and back on the low RPM circuit "Pool" it turns the green light back on showing the pool is running.

![image](https://user-images.githubusercontent.com/22131916/227972632-1535ba5f-1d0e-4510-9256-24b555648827.png)

**Comment by tagyoureit** [comment]
You will want to set it up such that your Filter circuit is always on and is the lowest speed of all circuits/features.  It is the circuit that controls whether or not the system thinks the pool is actually running.   Then, you can have the higher speed circuits override the lower ones.  It's backwards from your thinking but is the proper way to set it up.  

Do this:
* Filter Circuit - don't stop
* Pool Circuit - 4am-7:59am

It's also perfectly fine to overlap the schedules (if you create more).  This will prevent the pump from stopping and re-priming (less energy and less wear on the equipment).  The highest rpm of all active circuits is the one that is used.

Also, I find that I don't need to run my pump 24x7.  Especially at only ~900rpm many components like flow switches and chlorinators won't register any flow.  41 watts sounds enticing, but running at double or triple the rpm for less hours makes my pool happier.  My chlorinator usually needs 1400rpm and 10-12 hours/day at that speed may be plenty.  There is so little water movement at your current speed it may not be effectively circulating for proper filtration.

**Comment by camaro4life18** [comment]
Thanks for the response. I'm still trying to figure out how I want to run the pool for the summer. I'm doing 3 cycles a day of 4 hours at 2000-2500 RPMs for the actual filter cycle, so I get 12 hours a day of filtration. The low RPM setting is really there to keep water flowing through my temp probes so when I start using the heater it can better determine when to turn on during the non-filter cycles.

Nevertheless, I set the "Pool" circuit to "Don't Stop" and it works in the sense that the pump still runs at the low RPM. Nixie is showing the pool is off, and is not updating temp readings. Even though the RPM is > 500 and the PSI is > 0. It does this after the Filter circuit shuts off.

**Comment by camaro4life18** [comment]
I also found it will show off if you just turn on/off another pump circuit manually. In this case I turned on/off the filter circuit and it now shows the pool as off.

![image](https://user-images.githubusercontent.com/22131916/229159064-372bb527-82c4-43e9-b503-22a06e1cad21.png)

**Comment by tagyoureit** [comment]
As long as the Pool circuit remains on, the Pool body will remain on.  I think I was trying to follow your naming logic and mixed up pool/filter.  But "Pool" is the name of your pool body.  Turning on the filter should not turn off the pool circuit.  If it is doing that, send us a [packet capture](https://github.com/tagyoureit/nodejs-poolController/wiki/How-to-capture-all-packets-for-issue-resolution#-dashpanel) and we can see why.

**Comment by camaro4life18** [comment]
Ok, here is the capture. Also I renamed the "Pool" circuit to "Always Run".
This is what I did in the capture.
1) Turned on the Always Run circuit
2) Waited for data pulls on temp, RPM, and PSI.
3) Turned on Filter circuit
4) Waited on RPM to come up
5) Turned off Filter Circuit (This is where it shows things are turned off and stops temp readings, however the Always Run circuit is technically on because the pump is running)
6) Turned off Always Run
7) Turned on Always Run

[replay (3).zip](https://github.com/rstrouse/nodejs-poolController-dashPanel/files/11159061/replay.3.zip)

**Comment by camaro4life18** [comment]
Looking at the logs myself, I am not sure what is wrong with the InfluxDB saying "Value not bound". I do get data in Influx.

Also I see where it can't read the pump max speed, which is defined...
![image](https://user-images.githubusercontent.com/22131916/230088809-9053c026-dd74-4af5-8f09-2dfc1d3e4f94.png)

**Comment by rstrouse** [comment]
You tagged the filter circuit to override the pool circuit.  Please go into the configuration and set it to Generic.  I am not quite sure what you are doing with this but I suspect the filter circuit is simply set up to run the skimmers at a higher rate.

**Comment by camaro4life18** [comment]
That fixed it, I didn't know how the circuit types affected how it worked.
Thanks for the help!
