### ISSUE TITLE
Not sure how to start dashPanel

### ISSUE THREAD

**Issue by jwtaylor310** [rstrouse/nodejs-poolController-dashPanel#7]
I'm new to this project so I may be missing something obvious....  I have a raspberry Pi connected to an Easytouch control panel via a USB to RS485 adapter.  I have installed nodejs-poolController-master and it appears to start without a problem, ending with "info: EasyTouch system config complete."  On the same Pi I have installed nodejs-poolController-dashPanel-master.  It appears to start normally ending with "info: Server is now listening on 0.0.0.0:5150".  How do access the "Dashpanel Client" window?  It seems like I have two servers (the controller and the dashPanel) but no client.  What am I missing?  

Thanks for making this HUGE project available!

**Comment by tagyoureit** [comment]
Hi, were you able to load up dashpanel at `http://[your_server]:5150`?

**Comment by jwtaylor310** [comment]
Thank you for the rapid response.

 

I reinstalled the dashPanel and now the web page comes up as expected.  However, that has revealed two new issues:

 

Clicking on any of the function buttons results in an “Error: General Error” box with message “circuit.get is not a function.  The stack trace shows:

 

TypeError: circuit.get is not a function

    at /home/pi/nodejs-poolController-master/web/services/state/State.ts:56:72

    at processTicksAndRejections (internal/process/task_queues.js:97:5)

 

The corresponding function does get processed … for example, turning on/off the Spa works but each click on the Spa button causes the error box to display.

 

The Controller shows the following:

 

Init state for Pool Controller

info: Server is now listening on 0.0.0.0:4200

info: Serial port: /dev/ttyUSB0 opened

info: Serial port: /dev/ttyUSB0 request to open succeeded without error

info: Found Controller Board EasyTouch2 8

info: Requesting easytouch configuration

Failed:{"bytesReceived":355,"success":14,"failed":1,"bytesSent":96}

warn: Message aborted after 4 attempt(s): 165,55,16,33,203,1,21,1,238

warn: Message aborted after 4 attempt(s): 165,55,16,33,203,1,22,1,239

info: EasyTouch system config complete.

127.0.0.1 GET /state/all?null {}

info: New socket client connected MRGpYXQ69ynOKlE5AAAA -- 127.0.0.1

127.0.0.1 GET /state/all?null {}

127.0.0.1 PUT /state/circuit/setState {"id":4,"state":false}

request:  {"id":4,"state":false}... id: 4  state: false isOn: undefined

error: circuit.get is not a function

 

 

The second problem is that if I attempt to connect to the dashPanel using a web browser on a different computer on the same network, it displays the background image (blue water drops) but none of the data fields fill in:

 



 

To fix this I tried to enter the host Pi’s IP address using the “Settings” window in the web browser.  The “Apply” button was greyed out and I couldn’t save the change.  I then manually edited the config.json file and at startup the dashPanel server now shows that it is listening on the server’s IP (instead of 0.0.0.0) but that didn’t fix the problem when browsing from another computer.

 

Any help will be most appreciated!

 

--John Taylor

**Comment by tagyoureit** [comment]
I have a fix for this.  Will push it up soon but working on a couple other things and they are now intertwined.  It will be pushed to the `next` branch of the main app until we push a new dot release.  I'll let you know when it's done.

**Comment by jwtaylor310** [comment]
I'm just getting started with this project so there is no time pressure from my side.  Whenever you can get to it will be OK with me!  Thanks....

**Comment by tagyoureit** [comment]
I pushed up a fix to the `next` branch of the main app.  You can grab that or wait until we publish a 6.0.1 release (but don't have a specific timeframe for that yet).

**Comment by jwtaylor310** [comment]
I'm not clear on how to install from a branch, so I'l wait for the 6.0.1 release.  Thanks!
