### ISSUE TITLE
SSDP doesn't populate connection properly with multiple servers running

### ISSUE THREAD

**Issue by tagyoureit** [rstrouse/nodejs-poolController-dashPanel#8]
I've noticed that when I have 2 servers up and running, dashPanel finds them.  However, when I pick the first one, it still populates the second one.  Bonus - the 2nd server doesn't have a port and not sure why.

![2020-09-13_14-58-56](https://user-images.githubusercontent.com/1646840/93029707-fa07b300-f5d1-11ea-98d6-70bf712cad45.png)

![2020-09-13_15-01-39](https://user-images.githubusercontent.com/1646840/93029716-0ee44680-f5d2-11ea-8504-72b45f8d7019.png)

![2020-09-13_14-59-05](https://user-images.githubusercontent.com/1646840/93029708-fc6a0d00-f5d1-11ea-905f-c6509983b99e.png)

**Comment by rstrouse** [comment]
This was pulling from a variable that was getting updated by each pool controller it found.  This has been fixed.  I could not replicate your issue with no port but I suspect this was running on port 80 which is a default port so the port # is not required or desired.

**Comment by rstrouse** [comment]
Closing as this has been fixed.
