### ISSUE TITLE
Message aborted after 6 attempts - Trying to actuate valve

### ISSUE THREAD

**Issue by theRealMCQwerty** [rstrouse/nodejs-poolController-dashPanel#85]
Hi,
Intellicenter i8PS - firmware 1.064.
njsPC: 8.0.1
dashPanel 8.0.0

I have a Valve Expansion card in my OCP which surfaces the additional valve relays in the 'Valves' section of 'Other Equipment' on the Intellicenter2.com config page. I have each of those valves mapped to a Feature Circuit, of which 'C BLK Wall Retu' is one.
Each of these feature circuits shows up correctly in DashPanel.
When I try to actuate any of the features mapped to valves controlled by the OCP, I get an error similar to the screenshot below (this one is for 'C BLK Wall Retu'):
![image](https://github.com/rstrouse/nodejs-poolController-dashPanel/assets/26889036/c83ae011-e09d-4029-906b-ca5089f6d45c)

If I actuate the valve via the feature on the Intellicenter2.com website, then everything works correctly and the green light appears in DashPanel against that particular feature.

Attached are two packet captures:

'Replay DashPanel' is when attempting to actuate via DashPanel with the failure.
[replay DashPanel.zip](https://github.com/rstrouse/nodejs-poolController-dashPanel/files/15379300/replay.DashPanel.zip)

'Replay Intellicenter' is when actuating successfully via the Intellicenter2.com interface and then turning the valve 'off' again.
[replay Intellicenter.zip](https://github.com/rstrouse/nodejs-poolController-dashPanel/files/15379311/replay.Intellicenter.zip)

These are all Intellivalves.

Any ideas?

Thanks!

**Comment by rstrouse** [comment]
> Any ideas?

Yes the two NAN at the end of the frame are supposed to be the checksum for the message.  You do not turn valves on or off in IntelliCenter, you actuate circuits that define how the valve should be positioned.   Your valve setups are correct however you have additional Nixie circuits defined as circuits that will not show up in IntelliCenter.  I suspect we probably are not ignoring the master setting (1) when sending the information to IntelliCenter and thus the message to turn on or off a circuit needs to be fixed.

I will fix this this weekend.

**Comment by theRealMCQwerty** [comment]
Great, thanks! So I think that also explains why adjusting lights via DashPanel is also not working?
![image](https://github.com/rstrouse/nodejs-poolController-dashPanel/assets/26889036/c6ad97a3-bad6-4ab7-bdbe-09804efda458)

**Comment by theRealMCQwerty** [comment]
Hi @rstrouse, Sorry to bug you, just wondered if this was still on your radar or if it turned out to be more work than originally expected?
Thanks!

**Comment by rstrouse** [comment]
It has not fallen off my radar and I think I have it sorted but I need to find some time to test it.  Perhaps I will get some time to finish up the testing tonight on this and another issue.

**Comment by rstrouse** [comment]
Pull njsPC.  The code was including Nixie circuits and features when it was communicating with IntelliCenter.  IntelliCenter knows nothing of those so the message formatting would fail.

**Comment by theRealMCQwerty** [comment]
I pulled the latest but I am getting a lot of compile errors:

![image](https://github.com/rstrouse/nodejs-poolController-dashPanel/assets/26889036/ad3efc15-cf21-448d-9c35-5d7d26106cff)

![image](https://github.com/rstrouse/nodejs-poolController-dashPanel/assets/26889036/b596a780-8df2-4ae2-9f93-8422b795aa97)

**Comment by rstrouse** [comment]
Hmmm.  Something isn't right with your installation.  Which version of nodejs do you have installed?

**Comment by theRealMCQwerty** [comment]
18.16.0

![image](https://github.com/rstrouse/nodejs-poolController-dashPanel/assets/26889036/fde1f02a-effd-4aa7-a577-a1f1e183caac)

**Comment by rstrouse** [comment]
Are you starting from PM2 or from the command line.  You may need to have it rebuild if it is using the cache the first time.

**Comment by theRealMCQwerty** [comment]
I do use pm2 but I tried building from the command line.

from njsPC dir:

```
git pull
npm i
npm run build
```

Then it fails to compile with the errors above.

Do I need to do a fresh install or something?

**Comment by rstrouse** [comment]
```
git pull
npm i
npm start
```

Do you see any errors or warnings on git pull or npm i?

**Comment by theRealMCQwerty** [comment]
Just tried again from the top.
Looks like there were some more recent changes that pulled down with my latest pull. No errors in the `pull`.
![njspc 1](https://github.com/rstrouse/nodejs-poolController-dashPanel/assets/26889036/1f1fb70e-0664-430f-8ea6-1f69129fff4a)

`npm i` looked like it worked but has vulnerabilities but I assumed last time I could ignore these.
I did try an `npm audit fix` but that didn't seem to work
![image](https://github.com/rstrouse/nodejs-poolController-dashPanel/assets/26889036/bdaebb7d-c4a9-49ab-adb8-b5c69bf8691e)

then tried `npm run build` again and got the same compile errors

![image](https://github.com/rstrouse/nodejs-poolController-dashPanel/assets/26889036/7b5b8466-7cf7-4015-b8bc-da80f588a4e0)

**Comment by rstrouse** [comment]
You should **never** run npm audit fix.  Sadly this bs actually causes more issues than it fixes.  Even with node core because it will **fix** things to unreleased software.  Delete the entire node_modules directory and do npm i again.

**Comment by theRealMCQwerty** [comment]
Arg! Ok:

![image](https://github.com/rstrouse/nodejs-poolController-dashPanel/assets/26889036/05470c1a-136b-423a-914c-1d2b013eeb26)

Then tried `npm run build` again:

![image](https://github.com/rstrouse/nodejs-poolController-dashPanel/assets/26889036/108260a9-8a62-4b74-8e79-e8d12a65bc1a)

**Comment by rstrouse** [comment]
Run the following command and post the results

`npm ls typescript`

**Comment by theRealMCQwerty** [comment]
![image](https://github.com/rstrouse/nodejs-poolController-dashPanel/assets/26889036/dd7d3820-db74-459b-9285-737ec151b7b0)

**Comment by rstrouse** [comment]
Is there anything else that has changed?  OS... etc.

**Comment by theRealMCQwerty** [comment]
I haven't updated anything on the pi for a long time. Ah, so I think this all started when the PM2 log ran my SD card out of space. I cleared off the space and it was about the time I was trying to get the pool open and working again. 
I had somehow lost my settings for REM so I had to reconfigure all of that. Then I tried to remember how to link it all back to njsPC. I think I figured that out again but then started having the issue with the NaN errors that I eventually got round to reporting. (Because I thought for a long time I had messed something up in linking it to REM).

I don't think any of that explains this though does it? Unless the lack-of-space crash corrupted something else. REM and DashPanel seem to be working fine though.

😕

**Comment by rstrouse** [comment]
Yeah I cannot understand why this is not working.  I have tried several things and cannot get it to fail.  You did delete the node_modules directory and try it... correct?

**Comment by theRealMCQwerty** [comment]
> You did delete the node_modules directory and try it... correct?

Yes. (Photographic evidence: https://github.com/rstrouse/nodejs-poolController-dashPanel/issues/85#issuecomment-2159117694) :-)

Do I need to start a fresh? If so, how 'fresh' do you think?

**Comment by rstrouse** [comment]
Copy the data directory from njsPC and delete the existing directory.  Then do a git clone on njsPC.  It is so odd that the typescript compiler is failing on that module.

**Comment by theRealMCQwerty** [comment]
@rstrouse  That got it to compile. I was able to copy the data folder back in and run successfully but...
![image](https://github.com/rstrouse/nodejs-poolController-dashPanel/assets/26889036/d2d6796c-8cb2-4f07-b939-783939bbc618)

Back to the original problem. 
I checked the repo and looks like @tagyoureit  reverted your changes with a more recent commit with comments `"Revert "Fix intellicenter circuit message when nixie circuits are included."`

**Comment by tagyoureit** [comment]
Ugh.  I pushed a bad commit and tried to undo it but Git got me again.  I likely reverted back one commit too far.  :(

**Comment by theRealMCQwerty** [comment]
@tagyoureit are you able to un-undo or do we need @rstrouse to re-commit the previous changes?

**Comment by tagyoureit** [comment]
Pull it again.  I re-did the changes from the prior commit.

**Comment by theRealMCQwerty** [comment]
Thanks @tagyoureit. Working now.
Thank you @rstrouse - everything is working now. No idea what that compile issue was about but thanks for sticking with it.
Closing issue.
Thanks again!
